// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5QBL0q4I9tasE4wGchouD0C1JF4gLczo',
    appId: '1:795463530459:web:476babcf13c0d7e27319fe',
    messagingSenderId: '795463530459',
    projectId: 'quiz-sample-7f940',
    authDomain: 'quiz-sample-7f940.firebaseapp.com',
    storageBucket: 'quiz-sample-7f940.appspot.com',
    measurementId: 'G-2LVCRLMMPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDshtFlvWivOCaYpIT4fiYHqOlj0-tMS9k',
    appId: '1:795463530459:android:6a7b5b7ed37c15147319fe',
    messagingSenderId: '795463530459',
    projectId: 'quiz-sample-7f940',
    storageBucket: 'quiz-sample-7f940.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUrbO0yynwOfkG_RPjCz72fDVnmiZjYZ0',
    appId: '1:795463530459:ios:2d8d487911c966507319fe',
    messagingSenderId: '795463530459',
    projectId: 'quiz-sample-7f940',
    storageBucket: 'quiz-sample-7f940.appspot.com',
    iosClientId:
        '795463530459-6arjjr6cp9sbspukdb2l1nrebu2qsg0u.apps.googleusercontent.com',
    iosBundleId: 'jp.nakanishi_s.ore_quiz.sampleQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUrbO0yynwOfkG_RPjCz72fDVnmiZjYZ0',
    appId: '1:795463530459:ios:2d8d487911c966507319fe',
    messagingSenderId: '795463530459',
    projectId: 'quiz-sample-7f940',
    storageBucket: 'quiz-sample-7f940.appspot.com',
    iosClientId:
        '795463530459-6arjjr6cp9sbspukdb2l1nrebu2qsg0u.apps.googleusercontent.com',
    iosBundleId: 'jp.nakanishi_s.ore_quiz.sampleQuiz',
  );
}
